<a href="https://colab.research.google.com/github/ozguevara/cbutp/blob/main/Dimensiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Entendiendo las dimensiones de los datos
scalar -> un solo dato
vector -> lista, vector, arreglo ( 1 dimension )
Matriz -> 2 Dimensiones
Tensor -> 3 o mas dimensiones

In [ ]:
import numpy as np

In [ ]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

In [ ]:
# Vector
x = np.array([42,3,5,3,6,7])
print(x.shape)
x.ndim

(6,)


1

Matriz

In [ ]:
x = np.array([[43,3,5,3,6,7], [66,54,5,343,6,7]])
print(x.shape)
x.ndim

(2, 6)


2

Tensor

In [ ]:
x = np.array([[[43,3,5,3,6,7], [66,54,5,343,6,7]], [[43,3,5,3,6,7], [66,54,5,343,6,7]], [[43,3,5,3,6,7], [66,54,5,343,6,7]], [[43,3,5,3,6,7], [66,54,5,343,6,7]]])
print(x.shape)
x.ndim

(4, 2, 6)


3

In [ ]:
x = np.array([[0,1],
         [2,3],
         [4,5],
         [6,7]
         ])
x.shape

(4, 2)

In [ ]:
x.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [ ]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
# Haciendo lo mismo pero con transpuesta
np.transpose(x)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [ ]:
x.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])